/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HospitalManagementSystem;
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author asus
 */
public class AddDiagnosisInformation extends javax.swing.JFrame {
      public int flag=0;
    /**
     * Creates new form AddDiagnosisInformation
     */
    public AddDiagnosisInformation() {
        initComponents();
        LabelPatientIDnotExist.setVisible(false);
        jLabelTypesWard.setVisible(false);
        jComboBoxTypesWard.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTypesWard = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextFieldPatientID = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelPatientIDnotExist = new javax.swing.JLabel();
        jTextFieldSymptoms = new javax.swing.JTextField();
        jTextFieldDiagnosis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxWardReq = new javax.swing.JCheckBox();
        jLabelTypesWard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1360, 600));
        setPreferredSize(new java.awt.Dimension(1360, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Symptom's");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 67, 23));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 75, 76, 20));

        jLabel3.setText("Diagnosis");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 91, 27));

        jComboBoxTypesWard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTypesWard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generel", "Normal", "VIP" }));
        getContentPane().add(jComboBoxTypesWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 83, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Diagnosis Information");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 19, 236, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/exit.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 550, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/save-icon--1.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));
        getContentPane().add(jTextFieldPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 76, 63, -1));

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 72, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 170, 1330, 58));

        LabelPatientIDnotExist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPatientIDnotExist.setForeground(new java.awt.Color(255, 0, 0));
        LabelPatientIDnotExist.setText("patient ID does not exist");
        getContentPane().add(LabelPatientIDnotExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 119, 184, -1));
        getContentPane().add(jTextFieldSymptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 187, -1));
        getContentPane().add(jTextFieldDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 187, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ward required?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, -1));

        jCheckBoxWardReq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxWardReq.setText("Yes");
        jCheckBoxWardReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWardReqActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxWardReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, -1, -1));

        jLabelTypesWard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTypesWard.setText("Types of ward");
        getContentPane().add(jLabelTypesWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/add new patient background.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBoxWardReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWardReqActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxWardReq.isSelected())
        {
            jLabelTypesWard.setVisible(true);
            jComboBoxTypesWard.setVisible(true);
        }
        else{
            jLabelTypesWard.setVisible(false);
            jComboBoxTypesWard.setVisible(false);   
        }
    }//GEN-LAST:event_jCheckBoxWardReqActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String PatientID=jTextFieldPatientID.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from patientinfo where PatientID='"+PatientID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first()){
                LabelPatientIDnotExist.setVisible(true);
                
            }
            else{
                LabelPatientIDnotExist.setVisible(false);
                flag=1;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Connection error!");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(flag==1){
            String PatientID=jTextFieldPatientID.getText();
            String Symptoms=jTextFieldSymptoms.getText();
            String Diagnosis=jTextFieldDiagnosis.getText();
            String WardRequired;
            String TypesWard;
            if(jCheckBoxWardReq.isSelected()){
                WardRequired="Yes";
                TypesWard=(String)jComboBoxTypesWard.getSelectedItem();
                
            }
            else{
                WardRequired="No";
                TypesWard="";
            }
            try{
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("insert into PatientReport values ('"+PatientID+"','"+Symptoms+"','"+Diagnosis+"','"+WardRequired+"','"+TypesWard+"')");
                JOptionPane.showMessageDialog(null,"Successfully Updated");
                setVisible(false);
                new AddDiagnosisInformation().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Connection error or Enter data correct format!");
            }
            
        }
        else{
              JOptionPane.showMessageDialog(null,"PatientID field is empty!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDiagnosisInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPatientIDnotExist;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxWardReq;
    private javax.swing.JComboBox<String> jComboBoxTypesWard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTypesWard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDiagnosis;
    private javax.swing.JTextField jTextFieldPatientID;
    private javax.swing.JTextField jTextFieldSymptoms;
    // End of variables declaration//GEN-END:variables
}
