/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HospitalManagementSystem;

import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class AddDoctorRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddDoctorRecord
     */
    public AddDoctorRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelSpecialistIn = new javax.swing.JLabel();
        jTextFieldSpecialistIn = new javax.swing.JTextField();
        jLabelRoomNo = new javax.swing.JLabel();
        jTextFieldRoomNo = new javax.swing.JTextField();
        jLabelContractNumber = new javax.swing.JLabel();
        jTextFieldContractNumber = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelEducationalInformation = new javax.swing.JLabel();
        jTextFieldEducationalInformation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1320, 600));
        setPreferredSize(new java.awt.Dimension(1360, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Add Doctor Record");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 11, 250, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/save-icon--1.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/exit.png"))); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 570, -1, -1));

        jLabelName.setText("Name");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 100, 118, 25));
        getContentPane().add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 102, 191, -1));

        jLabelSpecialistIn.setText("Specialist In");
        getContentPane().add(jLabelSpecialistIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 153, 101, 26));
        getContentPane().add(jTextFieldSpecialistIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 156, 191, -1));

        jLabelRoomNo.setText("Room No");
        getContentPane().add(jLabelRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 230, 101, 27));
        getContentPane().add(jTextFieldRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 233, 191, -1));

        jLabelContractNumber.setText("Contract Number");
        getContentPane().add(jLabelContractNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 300, 101, 25));
        getContentPane().add(jTextFieldContractNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 302, 191, -1));

        jLabelAddress.setText("Address");
        getContentPane().add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 368, 101, 42));
        getContentPane().add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 368, 428, 42));

        jLabelEducationalInformation.setText("Educational Information");
        getContentPane().add(jLabelEducationalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 440, 127, 28));
        getContentPane().add(jTextFieldEducationalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 428, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HospitalManagementSystem/add new patient background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String PatientID=jTextField7.getText();
        String Name=jTextFieldName.getText();
        String SpecialistIn=jTextFieldSpecialistIn.getText();
        String ContractNumber=jTextFieldContractNumber.getText();
        String Address=jTextFieldAddress.getText();
        String EducationalInformation=jTextFieldEducationalInformation.getText();
        String RoomNo=jTextFieldRoomNo.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into doctorinfo values('"+Name+"','"+SpecialistIn+"','"+ContractNumber+"','"+Address+"','"+EducationalInformation+"','"+RoomNo+"')");
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            setVisible(false);
            new AddDoctorRecord().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection error or Enter data in right formate");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelContractNumber;
    private javax.swing.JLabel jLabelEducationalInformation;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRoomNo;
    private javax.swing.JLabel jLabelSpecialistIn;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldContractNumber;
    private javax.swing.JTextField jTextFieldEducationalInformation;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldRoomNo;
    private javax.swing.JTextField jTextFieldSpecialistIn;
    // End of variables declaration//GEN-END:variables
}
